POST http://localhost:3001/api/blogs
Content-Type: application/json

{
  "title": "Test Blogging: An exercise in humility",
  "author": "Abi N",
  "url": "https://abigail-illustration.com",
  "likes": 4
}